import { describe, expect, test } from '@jest/globals'
import parseLock, { Package } from './lockdiff'

const expectLock = (parsed: Package[], expected: string[][]): void => {
  const expectedPackages = expected.map(
    nameVersion => ({ name: nameVersion[0], version: nameVersion[1] })
  )
  expect(parsed).toStrictEqual(expectedPackages)
}

describe('parsing locks', () => {
  test('yarn.lock', () => {
    const contents = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


leftpad@^0.0.1:
  version "0.0.1"
  resolved "https://registry.yarnpkg.com/leftpad/-/leftpad-0.0.1.tgz#86b1a4de4face180ac545a83f1503523d8fed115"
  integrity sha512-kBAuxBQJlJ85LDc+SnGSX6gWJnJR9Qk4lbgXmz/qPfCOCieCk7BgoN3YvzoNr5BUjqxQDOQxawJJvXXd6c+6Mg==

typescript@^4.9.5:
  version "4.9.5"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-4.9.5.tgz#095979f9bcc0d09da324d58d03ce8f8374cbe65a"
  integrity sha512-1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==

    `.trim()

    const parsed = parseLock(contents, { name: 'yarn.lock' })


    expectLock(parsed,
      [
        ['leftpad', '0.0.1'],
        ['typescript', '4.9.5']
      ])
  })

  test('npm-package.lock', () => {
    const contents = `
    {
  "name": "my-proj",
  "version": "0.0.0",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "my-proj",
      "version": "0.0.0",
      "dependencies": {
        "@eslint": "^2.1.2"
      }
    },
    "node_modules/@eslint/eslintrc": {
      "version": "2.1.2",
       "resolved": "https://registry.npmjs.org/@eslint/eslintrc/-/eslintrc-2.1.2.tgz"
    }
  }
}
    `
    const parsed = parseLock(contents, { name: 'package-lock.json' })

    expectLock(parsed, [
      ['@eslint/eslintrc', '2.1.2']
    ])

  })
})


